### ISSUE TITLE
 AttributeError: class Extension has no attribute '__mro__'

### ISSUE THREAD

**Issue by elmorg** [pupil-labs/PyAV#4]
**Hi, I'm getting the following error trying to install PyAv on Mac 10.11.6. Have attempted to find a solution, to no avail.**

Installing collected packages: av
  Running setup.py install for av ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/c3/rzm70j7932dghy0rbn2231j80000gp/T/pip-8ynh_L-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/c3/rzm70j7932dghy0rbn2231j80000gp/T/pip-I5_d_J-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-2.7
    creating build/lib.macosx-10.11-x86_64-2.7/av
    copying av/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/av
    copying av/__main__.py -> build/lib.macosx-10.11-x86_64-2.7/av
    creating build/lib.macosx-10.11-x86_64-2.7/av/audio
    copying av/audio/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/av/audio
    creating build/lib.macosx-10.11-x86_64-2.7/av/container
    copying av/container/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/av/container
    creating build/lib.macosx-10.11-x86_64-2.7/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/av/subtitles
    creating build/lib.macosx-10.11-x86_64-2.7/av/video
    copying av/video/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/av/video
    running build_ext
    running reflect
    running config
    looking for avformat_open_input... found
    looking for pyav_function_should_not_exist... missing
    looking for av_calloc... found
    looking for av_frame_get_best_effort_timestamp... found
    looking for avformat_alloc_output_context2... found
    looking for avformat_close_input... found
    looking for AVStream.index... found
    looking for PyAV.struct_should_not_exist... missing
    looking for AVFrame.mb_type... missing
    writing build/temp.macosx-10.11-x86_64-2.7/include/pyav/config.h
    running cythonize
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c3/rzm70j7932dghy0rbn2231j80000gp/T/pip-8ynh_L-build/setup.py", line 715, in <module>
        distclass=distclass,
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/c3/rzm70j7932dghy0rbn2231j80000gp/T/pip-8ynh_L-build/setup.py", line 657, in run
        self.run_command('cythonize')
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/c3/rzm70j7932dghy0rbn2231j80000gp/T/pip-8ynh_L-build/setup.py", line 575, in run
        include_path=ext.include_dirs,
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 809, in cythonize
        aliases=aliases)
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 648, in create_extension_list
        elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 144, in __instancecheck__
        return cls.__subclasscheck__(subtype)
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 161, in __subclasscheck__
        ok = cls.__subclasshook__(subclass)
      File "/usr/local/lib/python2.7/site-packages/backports_abc.py", line 66, in __subclasshook__
        mro = C.__mro__
    AttributeError: class Extension has no attribute '__mro__'
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/c3/rzm70j7932dghy0rbn2231j80000gp/T/pip-8ynh_L-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/c3/rzm70j7932dghy0rbn2231j80000gp/T/pip-I5_d_J-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/c3/rzm70j7932dghy0rbn2231j80000gp/T/pip-8ynh_L-build/

**Comment by mkassner** [comment]
this looks like a cython error? 
what version of cython are you using?

**Comment by elmorg** [comment]
I thought the same. I have the most recent version (0.25.1) and have tried re-installing it.

**Comment by mkassner** [comment]
mayby try an older version. I m using '0.23.4'

**Comment by elmorg** [comment]
Success with version 0.23.4. Cheers.

**Comment by papr** [comment]
We will add an appropriate note to the docs. Thank you very much.
